### ISSUE TITLE
Bug Tracker

### ISSUE THREAD

**Issue by m-hodges** [m-hodges/anipers#6]
- [x] Animated Spinner bugs out on multiple spins - is it not being cleaned up properly in the useEffect?

- [x] Flicker on app load, need delay on visibility of underlying components.

- [x] App lagging from drawing too much on load

- [x] Show loading instead of previous tags images when going to Tags page with new tag - at the moment the previous tags show their until the next tags replace them - same issue with images

- [x] Prune unneeded data from images map and cache - app hard crashes when too many images are cached **breaking**

- [x] Scrolling from initialScrollTo index in FlatList resets after a few images **breaking**

- [x] Cropping

- [x] Cropping - in saved, and in home modes

- [x] Cropping compresses image so much it ruins quality - most likely due to original image dimensions being far greater than phone screen size dimensions - investigate lossless scaling (as react-native seems to do this natively with scaling the initial image preview) **breaking**

- [x] Settle data to store for images - and use it to unify image displays throughout app

- [x] Initial load issues for homepage wallpapers and saved wallpapers

- [x] Initial creation of the first item in references file

- [x] Wallpaper: Going back as the first action in horizontal scroll list - only happens if you do it too fast, if scroll slow its fine

- [x] Results: Clicking on background image errors

**Comment by m-hodges** [comment]
Ideas for scrollTo
- try initialListSize
- try ref, with a useEffect and if(ref.current) {scrollTo(index)}

**Comment by m-hodges** [comment]
https://github.com/ivpusic/react-native-image-crop-picker/issues/1085
- experiment with retaining original size of image
